engines:
  rubocop: { enabled: true  }
  fixme:   { enabled: false }
exclude_paths:
- .rubocop.yml
- .codeclimate.yml
- .travis.yml
- .gitignore
- .rspec

- Gemfile.lock
- CHANGELOG.{md,markdown,txt,textile}
- CONTRIBUTING.{md,markdown,txt,textile}
- readme.{md,markdown,txt,textile}
- README.{md,markdown,txt,textile}
- Readme.{md,markdown,txt,textile}
- ReadMe.{md,markdown,txt,textile}
- COPYING
- LICENSE

- site/**/*
- test/**/*
- vendor/**/*
- features/**/*
- script/**/*
- spec/**/*
ratings:
  paths:
  - lib/**/*.rb
