engines:
  fixme:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-54

exclude_paths:
  - "*.*"
  - ".*"

  - Gemfile
  - LICENSE
  - Rakefile

  - benchmark/**/*
  - features/**/*
  - script/**/*
  - exe/**/*
  - docs/**/*
  - rake/**/*
  - spec/**/*
  - test/**/*
  - vendor/**/*

  - lib/blank_template/**/*
  - lib/site_template/**/*
  - lib/theme_template/**/*
  - lib/jekyll/mime.types
  - lib/jekyll/commands/serve/livereload_assets/livereload.js

ratings:
  paths:
    - lib/**/*.rb
