Metrics/MethodLength: { Max:  24 }
Metrics/ClassLength:  { Max: 240 }
Metrics/ModuleLength: { Max: 240 }
Metrics/LineLength:   { Max: 112 }

Style/IndentHash: { EnforcedStyle: consistent }
Style/HashSyntax: { EnforcedStyle: hash_rockets }
Style/SignalException: { EnforcedStyle: only_raise }
Style/SpaceAroundOperators: { AllowForAlignment: true }
Style/AlignParameters: { EnforcedStyle: with_fixed_indentation }
Style/StringLiteralsInInterpolation: { EnforcedStyle: double_quotes }
Style/MultilineOperationIndentation: { EnforcedStyle: indented }
# Style/StringLiterals: { EnforcedStyle: double_quotes }
Style/RegexpLiteral: { EnforcedStyle: percent_r }
Style/IndentArray: { EnforcedStyle: consistent }

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%q': '{}'
    '%Q': '{}'
    '%r': '!!'
    '%s': '()'
    '%w': '()'
    '%W': '()'
    '%x': '()'

Style/StringLiterals:                 { Enabled: false }
Style/Documentation:                  { Enabled: false }
Style/DoubleNegation:                 { Enabled: false }
Style/UnneededCapitalW:               { Enabled: false }
Style/EmptyLinesAroundModuleBody:     { Enabled: false }
Style/EmptyLinesAroundAccessModifier: { Enabled: false }
Style/BracesAroundHashParameters:     { Enabled: false }
Style/SpaceInsideBrackets:            { Enabled: false }
Style/IfUnlessModifier:               { Enabled: false }
Style/ModuleFunction:                 { Enabled: false }
Style/RescueModifier:                 { Enabled: false }
Style/GuardClause:                    { Enabled: false }
Style/FileName:                       { Enabled: false }

AllCops:
  Include:
    - lib/**/*.rb

  Exclude:
    - .rubocop.yml
    - .codeclimate.yml
    - .travis.yml
    - .gitignore
    - .rspec

    - Gemfile.lock
    - CHANGELOG.md
    - readme.md
    - README.md
    - Readme.md
    - ReadMe.md
    - COPYING
    - LICENSE

    - test/**/*
    - vendor/**/*
    - features/**/*
    - script/**/*
    - spec/**/*
