language: ruby
cache: bundler
sudo: false
rvm:
- 2.2
- 2.1
- 2.0
- ruby-head
- jruby-9.0.3.0
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.3.0
  exclude:
    - rvm: jruby-9.0.3.0
      env: TEST_SUITE=cucumber
env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber
branches:
  only:
    - master
before_script: bundle update
script: script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
      - irc.freenode.org#jekyll
    template:
      - "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
  email:
    recipients:
      - jordon@envygeeks.io
    on_success: never
    on_failure: always
  slack:
    secure: dNdKk6nahNURIUbO3ULhA09/vTEQjK0fNbgjVjeYPEvROHgQBP1cIP3AJy8aWs8rl5Yyow4YGEilNRzKPz18AsFptVXofpwyqcBxaCfmHP809NX5PHBaadydveLm+TNVao2XeLXSWu+HUNAYO1AanCUbJSEyJTju347xCBGzESU=
