language: ruby

cache: bundler

sudo: false

rvm:
  - 2.1
  - 2.0
  - 1.9.3

env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber

before_script: bundle update

script: script/cibuild

notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} (%{branch}) %{message} %{build_url}'
  email:
    on_success: never
    on_failure: never
