# https://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

branches:
  only:
    - master
    - themes

build: off

install:
  - SET PATH=C:\Ruby%RUBY_FOLDER_VER%\bin;%PATH%
  - bundle install --retry 5

environment:
  BUNDLE_WITHOUT: "benchmark:site:development"
  matrix:
    - RUBY_FOLDER_VER: "23"
      GEMS_FOLDER_VER: "2.3.0"
      TEST_SUITE: "test"
    - RUBY_FOLDER_VER: "23"
      GEMS_FOLDER_VER: "2.3.0"
      TEST_SUITE: "cucumber"
    - RUBY_FOLDER_VER: "23"
      GEMS_FOLDER_VER: "2.3.0"
      TEST_SUITE: "fmt"
    - RUBY_FOLDER_VER: "23"
      GEMS_FOLDER_VER: "2.3.0"
      TEST_SUITE: "default-site"
    - RUBY_FOLDER_VER: "23-x64"
      GEMS_FOLDER_VER: "2.3.0"
      TEST_SUITE: "test"
    - RUBY_FOLDER_VER: "22"
      GEMS_FOLDER_VER: "2.2.0"
      TEST_SUITE: "test"
    - RUBY_FOLDER_VER: "21"
      GEMS_FOLDER_VER: "2.1.0"
      TEST_SUITE: "test"

test_script:
  - ruby --version
  - gem --version
  - bundler --version
  - bash ./script/cibuild

cache:
  # If one of the files after the right arrow changes, cache will be skipped
  - C:\Ruby%RUBY_FOLDER_VER%\bin -> Gemfile,jekyll.gemspec,appveyor.yml
  - C:\Ruby%RUBY_FOLDER_VER%\lib\ruby\gems\%GEMS_FOLDER_VER% -> Gemfile,jekyll.gemspec,appveyor.yml
