name: Build and deploy Jekyll documentation site
on:
  pull_request:
    branches:
      - master
jobs:
  deploy_docs:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Set up dependencies
        run: bash .github/actions/bootstrap
      - name: Build and Deploy
        run: bash .github/actions/deploy_docs
        env:
          JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
